packet: rename offset_to_ptr to skb_offset_to_ptr to avoid conflicts with newer kernel
Rename offset_to_ptr to skb_offset_to_ptr to avoid definition conflict
when building jool against linux >= 4.19.

Fixes:
| mod/stateful/../common/packet.c:73:14: error: conflicting types for 'offset_to_ptr'
|  static void *offset_to_ptr(struct sk_buff *skb, unsigned int offset)
|               ^~~~~~~~~~~~~
| In file included from kernel-source/include/linux/export.h:45,
|                  from kernel-source/include/linux/linkage.h:7,
|                  from kernel-source/include/linux/kernel.h:7,
|                  from kernel-source/include/linux/skbuff.h:17,
|                  from mod/stateful/../../include/nat64/mod/common/packet.h:81,
|                  from mod/stateful/../common/packet.c:1:
| kernel-source/include/linux/compiler.h:297:21: note: previous definition of 'offset_to_ptr' was here
|  static inline void *offset_to_ptr(const int *off)
|                      ^~~~~~~~~~~~~

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>